name: alarm_app
description: A beautiful alarm app built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.2
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  uuid: ^4.2.1
  file_picker: ^8.0.0
  google_fonts: ^6.1.0
  battery_plus: ^6.0.1
  home_widget: ^0.6.0
  flutter_svg: ^2.0.9
  path_provider: ^2.1.2
  vibration: ^3.1.2
  http: ^1.2.2
  youtube_explode_dart: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/ringtones/
    - assets/RALA ALARM LOGO.png
    - assets/logo RALA.png

flutter_icons:
  android: true
  ios: false
  image_path: assets/logo RALA.png
